server:
    port: 8100
spring:
  thymeleaf:
    encoding: utf-8
    #热部署静态文件
    cache: false
    #使用HTML5标准
    mode: HTML5
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost/jpademo?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
